services:
    postgres:
        image: "postgres:15.2"
        ports:
            - "5432"
        environment:
            - "POSTGRES_USER=postgresql_user"
            - "POSTGRES_DB=postgresql_db"
            - "POSTGRES_PASSWORD=postgresql_password"
