### Get Product
GET http://localhost:8080/api/products
Accept: application/json


### Create Product
POST http://localhost:8080/api/products
Content-Type: application/json

{
    "name": "Product {{$random.integer()}}",
    "description": "Product Description",
    "price_usd": {{$random.integer()}},
    "stock": {{$random.integer()}}
}
###